version: '3.4'

services:
  masstut.keeper:
    image: ${DOCKER_REGISTRY-}masstutkeeper
    build:
      context: .
      dockerfile: src/MassTut.Keeper/Dockerfile

  masstut.columbus:
    image: ${DOCKER_REGISTRY-}masstutcolumbus
    build:
      context: .
      dockerfile: src/MassTut.Columbus/Dockerfile

