version: '3.4'
services:
  masstut.keeper:
    environment:
      - "RabbitMQ__Host=event-bus"
      - "RabbitMQ__Username=guest"
      - "RabbitMQ__Password=guest"
      - "RabbitMQ__VirtualHost=/"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    
  masstut.front:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
