version: '3.4'

services:
  masstut.keeper:
    image: ${DOCKER_REGISTRY-}masstutkeeper
    build:
      context: .
      dockerfile: src/MassTut.Keeper/Dockerfile

  masstut.front:
    image: ${DOCKER_REGISTRY-}masstutfront
    build:
      context: .
      dockerfile: src/MassTut.Front/Dockerfile

  event-bus:
    image: rabbitmq:3.8-alpine
    hostname: event-bus    
