version: '3.4'

services:
  masstut.keeper:
    image: ${DOCKER_REGISTRY-}masstutkeeper
    build:
      context: .
      dockerfile: src/MassTut.Keeper/Dockerfile
  
  masstut.gate:
    image: ${DOCKER_REGISTRY-}masstutgate
    build:
      context: .
      dockerfile: src/MassTut.Gate/Dockerfile

  event-bus:
    image: rabbitmq:3.8-alpine
    hostname: event-bus
  